name: app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.1+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Logica
  rxdart: ^0.23.1

  # WordPress
  flutter_wordpress: ^0.1.4

  # Grafica
  cached_network_image: ^2.0.0
  font_awesome_flutter: ^8.8.1

  # UtilitÃ 
  html: ^0.14.0+3
  webview_flutter: ^0.3.19+9
  flutter_html: ^0.11.1
  shared_preferences: ^0.5.6+3
  share: ^0.6.3+6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.4
  r_flutter: ^0.6.0
  # flutter packages pub run r_flutter:generate

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path: "assets/ic_launcher.png"
  android: true
  ios: false